### PR TITLE
Microservice support

### LINKED ISSUE #43: Add Microservice Project Support

### PR DESCRIPTION
**Pull request by murdos**
Fixes #43 

With compatibility with Gateway generated by JHipster and JHipster Registry.
Sample JDL for use with this feature: https://gist.github.com/murdos/fb33326ea1db672e17ae2bb7479bd971

### CODE REVIEW

**Comment by JasonTypesCodes** [comment]
Excellent work @murdos.  It looks like we have a few CI failures.  One of which is because the server tests assumes that webpack is there.  I think we can just remove `-x webpack -x webpackBuildDev` from `./gradlew test integrationTest -x webpack -x webpackBuildDev` to move past that.  I only put that there to make the server tests fail sooner :)

**Comment by murdos** [comment]
FYI I've fixed CI build with gradle, so this PR is ready for review 😉

**Review by atomfrede — APPROVED** [review]
Huge work @murdos! Don't forget to claim your bounty, well deserved! We need to add microservice support to the readme afterwards. Let's merge this.

**Comment by atomfrede** [comment]
:facepalm: Going to do a new PR pointing to main.

**Comment by murdos** [comment]
bounty claimed: https://opencollective.com/generator-jhipster/expenses/34052

**Comment by pascalgrimaud** [comment]
@murdos : approved

**Pull request merged**
