### PR TITLE
Upgrade to JHipster 7.9.3

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
Lots of failures on this one. I'm adding a bug bounty in hopes someone knows how to fix it. 

/cc @jeremyg484 @mshima @kevintanhongann

**Comment by mshima** [comment]
@mraible done https://github.com/jhipster/generator-jhipster-micronaut/pull/282.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/163437.

**Comment by DanielFran** [comment]
@mshima approved

**Comment by mshima** [comment]
Thanks @DanielFran

**Pull request closed without merging**
