### PR TITLE
Upgrade to JHipster 8.1.0

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mshima** [comment]
@mraible we can stop setting the version so next version don't need adjust https://github.com/jhipster/generator-jhipster-micronaut/pull/321.

**Comment by mraible** [comment]
@mshima Are you saying that your PR (#321) replaces this one? If so, where is the JHipster version set? Is it only in `package.json` now?

**Comment by mshima** [comment]
> @mshima Are you saying that your PR (#321) replaces this one? If so, where is the JHipster version set? Is it only in `package.json` now?

It uses the default `jhipsterDependenciesVersion` provided by generator-jhipster.
It will match the generator-jhipster/jhipster-bom version.
A custom version was added due to v8 migration to keep v7 bom to make transition easier.

**Comment by mshima** [comment]
You can see the compare-sample step diff.

Captura de Tela 2024-02-26 às 14 00 47

**Pull request closed without merging**
