### PR TITLE
update main generator to 6.10.4

### LINKED ISSUE #180: React Build Failing (Cannot find name 'Cheerio'.)
The React build seems to be failing in master due to the following:

```
ERROR  Failed to compile with 2 errors2:45:54 PM

 error  in /home/runner/work/generator-jhipster-micronaut/generator-jhipster-micronaut/sample-output/gradle-jwt-react/node_modules/@types/enzyme/index.d.ts

ERROR in /home/runner/work/generator-jhipster-micronaut/generator-jhipster-micronaut/sample-output/gradle-jwt-react/node_modules/@types/enzyme/index.d.ts(384,15):
TS2304: Cannot find name 'Cheerio'.

 error  in /home/runner/work/generator-jhipster-micronaut/generator-jhipster-micronaut/sample-output/gradle-jwt-react/node_modules/@types/enzyme/index.d.ts

ERROR in /home/runner/work/generator-jhipster-micronaut/generator-jhipster-micronaut/sample-output/gradle-jwt-react/node_modules/@types/enzyme/index.d.ts(732,69):
TS2304: Cannot find name 'Cheerio'.
```

https://github.com/jhipster/generator-jhipster-micronaut/blob/master/test-integration/samples/gradle-jwt-react.jdl

### PR DESCRIPTION
**Pull request by atomfrede**
this should closes #180

### CODE REVIEW

**Comment by JasonTypesCodes** [comment]
@atomfrede would you mind deleting `test-integration/samples/fixes/gradle-jwt-react/package.json` as part of this?

It may also be worth going through the other dependencies in package.json once alongside the dependencies in 6.10.4 to make sure those revisions match (if you haven't done so already)

**Comment by JasonTypesCodes** [comment]
I think we should cut a 0.6.0 release after this :)

**Comment by atomfrede** [comment]
Removed the fix and update some of the dependencies which should be save. I think we should not diverge to much from the 6.x branch.

**Comment by JasonTypesCodes** [comment]
> Removed the fix and update some of the dependencies which should be save. I think we should not diverge to much from the 6.x branch.

Agreed.  :)  I just meant updating our dependencies to match the ones upstream

**Pull request merged**
