### PR TITLE
Updates Micronaut to 2.5.5

### PR DESCRIPTION
**Pull request by JasonTypesCodes**
Also: 
Closes: #252

### CODE REVIEW

**Comment by JasonTypesCodes** [comment]
It seems there is an issue creating some records.  I'll have to check into that a bit later on

**Comment by atomfrede** [comment]
:+1: You rock.

**Comment by mraible** [comment]
@JasonTypesCodes Can you please update for Micronaut 3?

**Comment by JasonTypesCodes** [comment]
> @JasonTypesCodes Can you please update for Micronaut 3?

That will be a bit more of a lift.  Something seems to be timing out with newer Micronaut Data and I haven't taken the time to figure out what that is.  I'll create a Micronaut 3 issue and I'll update this PR to the latest 2.5.x

**Comment by atomfrede** [comment]
@JasonTypesCodes I will try to update to micronaut 3.x as the update to jhipster 7 is done. Going to close this one here for now. @mraible If you like you can put a bounty on https://github.com/jhipster/generator-jhipster-micronaut/issues/259. I guess there will be a lot of improvements to native support to.

**Pull request closed without merging**
