### PR TITLE
Upgrade to JHipster 8.2

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
When I run `mhipster --defaults` in this branch, it results in the following error:

```
ERROR! An error occured while running jhipster:liquibase#customizeMaven
ERROR! ERROR! Cannot read properties of undefined (reading 'liquibase')
TypeError: Cannot read properties of undefined (reading 'liquibase')
```

**Comment by mraible** [comment]
I give up for now. Please fix if you know how.

**Comment by mraible** [comment]
@mshima This one seems to be failing on oauth2 projects with the following error. Any ideas?

```
ERROR! An error occured while running jhipster-micronaut:server#writeFiles
ERROR! ERROR! /home/runner/work/generator-jhipster-micronaut/generator-jhipster-micronaut/generator-jhipster-micronaut/generators/server/templates/src/main/java/_package_/domain/User.java.ejs:47
    45|     @GeneratedValue(strategy = UNIQUE, delimiter = ID_DELIMITER)
    46| <%_ } _%>
 >> 47|     private <%= user.primaryKey.type %> id;
    48| 
    49|     @NotNull
    50|     @Pattern(regexp = Constants.LOGIN_REGEX)
```

**Comment by mraible** [comment]
Fixed by #326.

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/203370.

**Pull request closed without merging**
