### PR TITLE
move config into templates

### PR DESCRIPTION
**Pull request by sendilkumarn**

### CODE REVIEW

**Comment by atomfrede** [comment]
@sendilkumarn What are the next steps to work on? Are you putting the sample application into templates? Which part is next? Would like to help here more

**Comment by sendilkumarn** [comment]
Thanks @atomfrede Sure, I am thinking of just porting the sample-app as an MVP and then move forward by adding more options.

**Comment by sendilkumarn** [comment]
WDYT?

**Comment by atomfrede** [comment]
:+1: Sounds like a plan. Should we track separate parts in own issues such that we don't work on same parts?

**Comment by sendilkumarn** [comment]
I prefer it to be in own issues.

**Pull request merged**
