### PR TITLE
React generator

### PR DESCRIPTION
**Pull request by ZacharyKlein**
Add React templates to generator.

### CODE REVIEW

**Comment by willbuck** [comment]
@ZacharyKlein I wasn't able to see an admin tab along the nav bar w/ this branch so I've pushed a change that adds it, however I'm still seeing issues w/ the health and config endpoints. I will look further at it tomorrow as I'm off for the day today!

**Comment by ZacharyKlein** [comment]
@willbuck Can you verify that you meant the "Metrics" page? That one seems to work fine for me. 

I have updated the Health and Configuration pages to render the Micronaut endpoint responses. Fixed several other misc bugs as well.

**Comment by willbuck** [comment]
I definitely meant Health and Config. As of your most recent commit everything looks to be working great! In fact, I think some of it is working better than the angular bits and I think I might have to take a closer look at those (I seem to recall some of the health keys seemed to be failing translation when I looked closer at the generated angular project, and I think the config data you're showing on the react side is more richly separated.)

I took the liberty of pushing a quick removal of the `audit` option in the admin menu though; I'm confident it doesn't exist in the sample app, I believe b/c James said we don't support audit just yet in micronaut.

This looks good to me, @atomfrede @sendilkumarn @jdubois have any of you had a chance to take a look?

**Comment by JasonTypesCodes** [comment]
@ZacharyKlein I have failing tests when I run `npm test`:
```
 FAIL  src/test/javascript/spec/app/shared/reducers/authentication.spec.ts (87 MB heap size)
  ● Authentication reducer tests › Actions › dispatches LOGIN, GET_SESSION and SET_LOCALE success and request actions

    TypeError: Cannot read property 'access_token' of undefined



      at src/main/webapp/app/shared/reducers/authentication.ts:1623:50
      at fulfilled (node_modules/tslib/tslib.js:147:26)

  ● Authentication reducer tests › clearAuthToken › clears the session token on clearAuthToken

    TypeError: Cannot read property 'access_token' of undefined



      at src/main/webapp/app/shared/reducers/authentication.ts:1623:50
      at fulfilled (node_modules/tslib/tslib.js:147:26)

  ● Authentication reducer tests › clearAuthToken › clears the local storage token on clearAuthToken

    TypeError: Cannot read property 'access_token' of undefined



      at src/main/webapp/app/shared/reducers/authentication.ts:1623:50
      at fulfilled (node_modules/tslib/tslib.js:147:26)

 FAIL  src/test/javascript/spec/app/shared/reducers/application-profile.spec.ts (95 MB heap size)
  ● Profile reducer tests › Common tests › should return the right payload in prod

    TypeError: Cannot read property 'includes' of undefined



      at Object.<anonymous>.exports.default (src/main/webapp/app/shared/reducers/application-profile.ts:339:49)
      at Object.<anonymous> (src/test/javascript/spec/app/shared/reducers/application-profile.spec.ts:30:21)

  ● Profile reducer tests › Common tests › should return the right payload in dev with swagger enabled

    TypeError: Cannot read property 'includes' of undefined



      at Object.<anonymous>.exports.default (src/main/webapp/app/shared/reducers/application-profile.ts:339:49)
      at Object.<anonymous> (src/test/javascript/spec/app/shared/reducers/application-profile.spec.ts:45:21)

```

**Comment by JasonTypesCodes** [comment]
I feel like we had similar failures on the Angular side.  Is that correct @willbuck?

**Comment by willbuck** [comment]
Yes @jasontypescodes essentially the react CUT has been changed but the test itself is not being replaced (at least that's my guess, not at my laptop atm).

Probably just need to copy the base gen react test and modify it to match our changes

**Comment by ZacharyKlein** [comment]
@JasonTypesCodes The test failures have been fixed - they were both related to changes I had made to the React components to work with the authentication and config endpoints from Micronaut, but hadn't made the corresponding changes in the relevant tests. They should all be passing now.

**Pull request merged**
