### PR TITLE
Add support for entity filtering, using micronaut-data-spring-jpa support for JpaSpecificationExecutor

### LINKED ISSUE #171: When importing JDL file: JpaSpecificationExecutor dependency not present in POM
##### **Overview of the issue**

After I imported a JDL file, every repository was missing the `JpaSpecificationExecutor` dependency

##### **Reproduce the error**

* Create a MN project
* Import a JDL file

##### **Related issues**

None

##### **Suggest a Fix**

add this to the pom file

```
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-jpa</artifactId>
    <version>2.2.7.RELEASE</version>
</dependency>
```

-   [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by murdos**
Fixes #171

It should be noted that the behavior of `xyz.in=someValue,otherValue` in REST query params is not supported (see https://github.com/micronaut-projects/micronaut-core/issues/2157), so instead `xyz.in=someValue&xyz.in=otherValue` should be used

### CODE REVIEW

**Comment by murdos** [comment]
This feature will require the merge and release of this fix to data-spring-jpa: https://github.com/micronaut-projects/micronaut-data/pull/773

**Comment by atomfrede** [comment]
Impressive @murdos how you find the time to implement all things you do! :+1:

**Comment by atomfrede** [comment]
For the failing gradle builds, can you check it uses `micronautVersion`? It seems it tries to use the old property `micronaut_version`

**Comment by murdos** [comment]
> 
> 
> For the failing gradle builds, can you check it uses `micronautVersion`? It seems it tries to use the old property `micronaut_version`

Good catch, thanks!

FWI this PR actually requires https://github.com/jhipster/generator-jhipster-micronaut/pull/201 and https://github.com/jhipster/generator-jhipster-micronaut/pull/202. Once they're merged I'll do some final tests with relationships filtering.

**Comment by mraible** [comment]
@murdos Can you please fix conflicts?

**Pull request closed without merging**
