### PR TITLE
Use JHipster 7.9.3 version, and eliminate the unnecessary dropwizard …

### PR DESCRIPTION
**Pull request by gzsombor**
…dependency

### CODE REVIEW

**Comment by mraible** [comment]
Adding a bug bounty for this because I looked into it and couldn't figure it out.

**Comment by mraible** [comment]
Increasing bug bounty in hopes of a weekend fix! :)

**Comment by gzsombor** [comment]
That's definitely tricky :D I've just understood, that the templates under templates_back are not used, but this blueprint use the same templates as generator-jhipster.
So this is definitely strange, how that could cause problem with bytea/lob types on PostgreSQL, but not on the mainline...

**Comment by mraible** [comment]
Could it be related to Liquibase? I noticed that this blueprint has its [own version](https://github.com/jhipster/generator-jhipster-micronaut/blob/main/generators/constants.cjs#L59) specified.

**Comment by mraible** [comment]
@mshima Any idea why tests are failing?

**Comment by gzsombor** [comment]
Probably, we still need FixedPostgreSQL10Dialect for blobs :wink:

**Comment by mshima** [comment]
FixedPostgreSQL10Dialect is not required https://github.com/mshima/generator-jhipster-micronaut/commit/ae7db10eadbf3dae8179b477935ed3d72f824215.
Create a startWith at liquibase may fix the user constraint id error, but seems to trigger others errors: https://github.com/mshima/generator-jhipster-micronaut/commit/ab46a21fe21625a7f31657810daa1578de78ac86

I've opened https://github.com/gzsombor/generator-jhipster-micronaut/pull/2 for reference, feel free to close or use.

**Comment by gzsombor** [comment]
Thanks, I will have a look on it @mshima !
Is there any documentation about the fragments, how do they work?

**Comment by gzsombor** [comment]
@mshima : that 'startsWith=1050' hack was not loved by the old h2database, which we still need to use on v7 maintenance, luckily, the userRepository.deleteAll() call was enough to fix the integration tests. 
I'm still not 100% sure that the settings used in DomainUserDetailsServiceIT is the best way to configure the tests and the transactions, but it does it's job... 
@mraible : I think, we can merge this :smile:

**Comment by mshima** [comment]
> Thanks, I will have a look on it @mshima !
> Is there any documentation about the fragments, how do they work?

The initial commit has explanations https://github.com/jhipster/generator-jhipster/pull/15494.

**Comment by mraible** [comment]
@gzsombor Please let me know if you'd still like me to merge this.

**Comment by gzsombor** [comment]
I think this is fine,as of now

**Review by mraible — APPROVED** [review]

**Comment by gzsombor** [comment]
Bounty claimed: https://opencollective.com/generator-jhipster/expenses/158062

thx

**Comment by DanielFran** [comment]
@gzsombor approved

**Pull request merged**
