### PR TITLE
Update to Jhipster v7

### PR DESCRIPTION
**Pull request by DanielFran**

### CODE REVIEW

**Comment by atomfrede** [comment]
Thanks @DanielFran. Micronaut 2.4.0 does not work, did not find out why, see here: https://github.com/jhipster/generator-jhipster-micronaut/pull/230

Can you revert that update, other changes should be fine, I postponed them for jhipster 7 but would also be okay to have them earlier.

**Comment by DanielFran** [comment]
@atomfrede done.
Not sure what is the problem with the mapper...

**Comment by atomfrede** [comment]
Something with mapstruct 1.3.x vs mapstruct 1.4.x maybe. But I would not expect such a compile exception.

**Comment by DanielFran** [comment]
@atomfrede Seems related with https://github.com/mapstruct/mapstruct/issues/1617

**Comment by DanielFran** [comment]
@atomfrede  Reverted for now the mapstruct update too.

**Comment by DanielFran** [comment]
@atomfrede I see that you are still targetting to old jhipster bom dependency.
Better to switch to the newer dependency after v7 is out

**Comment by atomfrede** [comment]
That was my plan :D We want to have first 1.0 release targeting still targeting JH6 and afterwards move to JH7

**Comment by atomfrede** [comment]
So let's park this

**Comment by mraible** [comment]
Can this be revisited now?

**Comment by DanielFran** [comment]
@mraible I will close this, since it is better to review all blueprint config, @mshima it is the expert and probably can take a look...

**Comment by mshima** [comment]
I’ve never used micronaut.
I can try to migrate the blueprint without updating dependencies.

**Comment by atomfrede** [comment]
@mshima or would say it's easier to start from scratch to incorporate all the changes done with jhipster 7? Such that we can have new version based on jh7 with micronaut 3.x directly?

**Comment by mshima** [comment]
@atomfrede I’ve started the migration.
- I am creating the generators from the ground.
- I moved out the clients templates, and started replacing existing files (like native blueprint). And reintegrating the ones that needs more extensive changes.
- I am adapting and reusing the backend templates.

The focus is to have cypress tests passing right now.

**Comment by atomfrede** [comment]
Awesome! You rock. Where do find the time to do all you are doing?! Anyways, if I can help somehow just let me know

**Comment by mshima** [comment]
@DanielFran I think this PR can be reopened and rebased.
I've updated to v7 without updating to jhipster-bom v7.
It would be insane migrate everything at once.

**Pull request closed without merging**
